#!/bin/bash
# postcompact-vaultsync.sh — SessionStart hook, matcher: compact
#
# Fires AFTER the harness auto-compacts (or after a manual /compact) and the
# model resumes on the compacted transcript. A hook is bash — it cannot itself
# invoke a Claude skill — so this hook's job is to INJECT an instruction (via
# stdout, which SessionStart hooks add to the model's context) telling the
# resumed model to:
#   1. run the vault-sync skill (CSJ's standing requirement on every compaction), and
#   2. verify/repair the PreCompact safety-net handover the sibling
#      precompact-handover.sh just wrote (it's a minimal git-only snapshot; the
#      model has the real "what was I doing" context the bash hook never had).
#
# This replaces the old UserPromptSubmit context-watch tripwire: instead of
# nagging the model to /context-handover before a hard cap, we let auto-compact
# do its thing and use this resume-time injection to keep the vault + handover correct.
#
# Output contract: SessionStart hooks emit context via stdout as
# {"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "..."}}.
# Plain stdout also works, but the JSON form is the documented, stable channel.

set -u

REPO_ROOT="/Users/CSJ/Desktop/fynla"
MONTH=$(date +%B)
DAY=$(date +%-d)
TARGET_FOLDER="${MONTH}/${MONTH}${DAY}Updates"
REPO_TARGET="${REPO_ROOT}/${TARGET_FOLDER}"

# Find the most recent precompact handover written today (sibling hook just made it).
LATEST_PRECOMPACT=$(ls -t "${REPO_TARGET}"/handover-*-precompact.md 2>/dev/null | head -1)

# Build the instruction the resumed model will act on.
read -r -d '' MSG <<EOF || true
COMPACTION JUST OCCURRED — two required follow-ups before continuing normal work:

1. **Run the vault-sync skill now.** Invoke Skill({skill:"vault-sync"}). This is
   CSJ's standing requirement on every compaction so the fynlaBrain vault stays
   current with the work that led up to the compaction. Do this BEFORE resuming
   the interrupted task.

2. **Verify and repair the auto-written handover.** The PreCompact hook wrote a
   minimal git-only safety-net handover at:
       ${LATEST_PRECOMPACT:-(none found in ${TARGET_FOLDER} — write a proper one)}
   That file was generated by bash and lacks the real narrative (it only has git
   status + recent commits + last 3 user prompts). YOU still hold the pre-compaction
   context in this resumed transcript. Open that file and rewrite its "Immediate
   state", "The thread", "Pick up from here", "Open decisions", and "What the next
   Claude needs to know" sections so it is a CORRECT, complete handover — matching
   the /context-handover template quality. Mirror the corrected copy to
   /Users/CSJ/Desktop/fynlaBrain/${TARGET_FOLDER}/ and commit it.

After both are done, continue the task the user was on before compaction.
EOF

# Emit via the documented SessionStart additionalContext channel (JSON), using
# python3 for safe escaping of the multi-line message.
python3 - "$MSG" <<'PY' 2>/dev/null || printf '%s\n' "$MSG"
import json, sys
msg = sys.argv[1]
print(json.dumps({
    "hookSpecificOutput": {
        "hookEventName": "SessionStart",
        "additionalContext": msg,
    }
}))
PY

exit 0
