@extends('emails.layouts.master', [
    'title'     => 'Clips ready — ' . $articleTitle,
    'preheader' => $clipCount . ' vertical clip' . ($clipCount === 1 ? '' : 's') . ' ready for review — ' . $articleTitle,
])

@section('logoBar')
    @include('emails.modules.logo-bar')
@endsection

@section('header')
    @include('emails.modules.hero-header', [
        'heading'  => 'Your clips<br/><span style="color:#f9a8c0;">are ready to review</span>',
        'subtitle' => 'Generated by Fynla Marketing Pipeline',
    ])
@endsection

@section('body')
    <tr>
        <td style="background:#f5f0eb;padding:28px 36px 8px;">
            <h2 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#1F2A44;">Hi Marketing team,</h2>
            <p style="margin:0 0 16px;font-size:14px;color:#555;line-height:1.7;">
                {{ $clipCount }} vertical (9:16) clip{{ $clipCount === 1 ? '' : 's' }} {{ $clipCount === 1 ? 'has' : 'have' }} been generated
                from the source video for <strong>{{ $articleTitle }}</strong>.
                Captions are burned in — the clips are ready to post to Instagram Reels, Facebook Reels and TikTok as-is.
            </p>
        </td>
    </tr>

    <tr>
        <td bgcolor="#fce4ec" style="background:#fce4ec;padding:28px 36px;">
            <h3 style="margin:0 0 10px;font-size:22px;font-weight:900;color:#1F2A44;line-height:1.2;">Review clips</h3>
            <p style="margin:0 0 18px;font-size:14px;color:#1F2A44;line-height:1.6;">
                Each clip is a signed download link valid for 30 days. Click to preview / download.
            </p>
            @foreach($clipUrls as $index => $url)
                <div style="margin-bottom:10px;">
                    <a href="{{ $url }}" style="display:inline-block;padding:10px 20px;background:#e74c6f;color:#ffffff;font-size:14px;font-weight:700;border-radius:8px;text-decoration:none;">
                        Clip {{ $index + 1 }} ({{ pathinfo(parse_url($url, PHP_URL_PATH), PATHINFO_BASENAME) }})
                    </a>
                </div>
            @endforeach
        </td>
    </tr>

    <tr>
        <td style="background:#f5f0eb;padding:24px 36px 8px;">
            <h3 style="margin:0 0 10px;font-size:20px;font-weight:700;color:#1F2A44;">Next steps</h3>
            <div style="background:#FAD6E0;border-radius:10px;padding:16px 20px;">
                <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="font-family:'Segoe UI',Inter,Arial,sans-serif;">
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;border-bottom:1px solid #e8e2db;">1.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;border-bottom:1px solid #e8e2db;">Preview each clip. If the framing or caption timing looks off, tell us — we can regenerate.</td>
                    </tr>
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;border-bottom:1px solid #e8e2db;">2.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;border-bottom:1px solid #e8e2db;">Download the clips you want to publish.</td>
                    </tr>
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;">3.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;">Post to Instagram / Facebook / TikTok, then update the row in the <a href="{{ $trackerUrl }}" style="color:#e74c6f;text-decoration:none;font-weight:700;">tracker sheet</a> with the platform links.</td>
                    </tr>
                </table>
            </div>

            <p style="margin:16px 0 0;font-size:12px;color:#7a7a7a;line-height:1.5;">
                Article slug: <code style="background:#e8e2db;padding:1px 4px;border-radius:3px;">{{ $articleSlug }}</code><br/>
                Source video length: {{ $durationSeconds ? gmdate('i:s', (int) $durationSeconds) : 'unknown' }} · Captions: burned in
            </p>
        </td>
    </tr>
@endsection

@section('signoff')
    @include('emails.modules.signoff', [
        'signoffText' => 'The Fynla Marketing Pipeline',
    ])
@endsection

@section('footer')
    @include('emails.modules.footer', ['variant' => 'dark'])
@endsection
