@extends('emails.layouts.master', [
    'title'     => 'Script ready — ' . $articleTitle,
    'preheader' => 'A 60-second video script has been generated for ' . $articleTitle . '. Review in Google Drive.',
])

@section('logoBar')
    @include('emails.modules.logo-bar')
@endsection

@section('header')
    @include('emails.modules.hero-header', [
        'heading'  => 'A new script<br/><span style="color:#f9a8c0;">is ready to review</span>',
        'subtitle' => 'Generated by Fynla Marketing Pipeline',
    ])
@endsection

@section('body')
    <tr>
        <td style="background:#f5f0eb;padding:28px 36px 8px;">
            <h2 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#1F2A44;">Hi Marketing team,</h2>
            <p style="margin:0 0 16px;font-size:14px;color:#555;line-height:1.7;">
                A 60-second video script has been drafted for the article
                <strong>{{ $articleTitle }}</strong>.
                It's saved as a Google Doc in the Marketing Automation folder — open it below,
                make any edits, then record the video and update the tracker sheet when it's ready.
            </p>
        </td>
    </tr>

    <tr>
        <td bgcolor="#fce4ec" style="background:#fce4ec;padding:28px 36px;">
            <h3 style="margin:0 0 10px;font-size:22px;font-weight:900;color:#1F2A44;line-height:1.2;">Open the script</h3>
            <p style="margin:0 0 18px;font-size:14px;color:#1F2A44;line-height:1.6;">
                Review, edit and comment directly in Google Docs.
            </p>
            <a href="{{ $scriptUrl }}" style="display:inline-block;padding:12px 28px;background:#e74c6f;color:#ffffff;font-size:14px;font-weight:700;border-radius:10px;text-decoration:none;">Open script in Google Docs</a>
        </td>
    </tr>

    <tr>
        <td style="background:#f5f0eb;padding:24px 36px 8px;">
            <h3 style="margin:0 0 10px;font-size:20px;font-weight:700;color:#1F2A44;">Next steps</h3>
            <div style="background:#FAD6E0;border-radius:10px;padding:16px 20px;">
                <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="font-family:'Segoe UI',Inter,Arial,sans-serif;">
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;border-bottom:1px solid #e8e2db;">1.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;border-bottom:1px solid #e8e2db;">Review + edit the script in Google Docs.</td>
                    </tr>
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;border-bottom:1px solid #e8e2db;">2.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;border-bottom:1px solid #e8e2db;">Record the video and upload it to the Marketing Automation folder.</td>
                    </tr>
                    <tr>
                        <td style="padding:8px 0;font-size:14px;font-weight:700;color:#1F2A44;">3.</td>
                        <td style="padding:8px 0;font-size:14px;color:#1F2A44;">Update the row in the <a href="{{ $trackerUrl }}" style="color:#e74c6f;text-decoration:none;font-weight:700;">tracker sheet</a> with the video link and status.</td>
                    </tr>
                </table>
            </div>

            <p style="margin:16px 0 0;font-size:12px;color:#7a7a7a;line-height:1.5;">
                Article slug: <code style="background:#e8e2db;padding:1px 4px;border-radius:3px;">{{ $articleSlug }}</code><br/>
                Model: {{ $model }} · Prompt: {{ $promptVersion }} · Cost: &pound;{{ $costGbp }}
            </p>
        </td>
    </tr>
@endsection

@section('signoff')
    @include('emails.modules.signoff', [
        'signoffText' => 'The Fynla Marketing Pipeline',
    ])
@endsection

@section('footer')
    @include('emails.modules.footer', ['variant' => 'dark'])
@endsection
