@extends('emails.layouts.master', [
    'title'     => 'Script ready — ' . $articleTitle,
    'preheader' => 'A 60-second video script has been generated for ' . $articleTitle . '. Review the article in the admin panel.',
])

@section('logoBar')
    @include('emails.modules.logo-bar')
@endsection

@section('header')
    @include('emails.modules.hero-header', [
        'heading'  => 'A new script<br/><span style="color:#f9a8c0;">is ready</span>',
        'subtitle' => 'Generated by Fynla Marketing Pipeline',
    ])
@endsection

@section('body')
    <tr>
        <td style="background:#f5f0eb;padding:28px 36px 8px;">
            <h2 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#1F2A44;">Hi Marketing team,</h2>
            <p style="margin:0 0 16px;font-size:14px;color:#555;line-height:1.7;">
                A 60-second video script has been generated for
                <strong>{{ $articleTitle }}</strong> and saved to the Marketing Automation folder
                in Google Drive. The script needs no approval &mdash; it's ready to use. The
                <strong>article</strong> is now waiting in the admin panel for you to review the
                formatting and push it to dev / live.
            </p>
        </td>
    </tr>

    <tr>
        <td bgcolor="#fce4ec" style="background:#fce4ec;padding:28px 36px;">
            <h3 style="margin:0 0 10px;font-size:20px;font-weight:700;color:#1F2A44;line-height:1.2;">The video script</h3>
            <p style="margin:0 0 18px;font-size:14px;color:#1F2A44;line-height:1.6;">
                Open it in Google Docs to read, edit or comment. Then record the video and drop it
                into the Marketing Automation &rsaquo; Videos folder.
            </p>
            <a href="{{ $scriptUrl }}" style="display:inline-block;padding:12px 28px;background:#e74c6f;color:#ffffff;font-size:14px;font-weight:700;border-radius:10px;text-decoration:none;">Open script in Google Docs</a>
        </td>
    </tr>

    <tr>
        <td style="background:#f5f0eb;padding:28px 36px;">
            <h3 style="margin:0 0 10px;font-size:20px;font-weight:700;color:#1F2A44;line-height:1.2;">Review &amp; publish the article</h3>
            <p style="margin:0 0 18px;font-size:14px;color:#1F2A44;line-height:1.6;">
                Check the formatting in the admin panel, then push it local &rarr; dev &rarr; live.
            </p>
            <a href="{{ $adminUrl }}" style="display:inline-block;padding:12px 28px;background:#1F2A44;color:#ffffff;font-size:14px;font-weight:700;border-radius:10px;text-decoration:none;">Open in the admin panel</a>

            <p style="margin:18px 0 0;font-size:12px;color:#7a7a7a;line-height:1.5;">
                Article slug: <code style="background:#e8e2db;padding:1px 4px;border-radius:3px;">{{ $articleSlug }}</code>
                @if($model)<br/>Model: {{ $model }} &middot; Cost: &pound;{{ $costGbp }}@endif
            </p>
        </td>
    </tr>
@endsection

@section('signoff')
    @include('emails.modules.signoff', [
        'signoffText' => 'The Fynla Marketing Pipeline',
    ])
@endsection

@section('footer')
    @include('emails.modules.footer', ['variant' => 'dark'])
@endsection
